CREATE TABLE FS_REPO
(
    ID DECIMAL(10,0) PRIMARY KEY NOT NULL,
    PATH VARCHAR(4000) NOT NULL
);
CREATE UNIQUE INDEX FS_REPO_PK ON FS_REPO (ID);

CREATE TABLE FS_BACKUP
(
    ID DECIMAL(10,0) PRIMARY KEY NOT NULL,
    PATH VARCHAR(4000) NOT NULL,
    REPO_ID DECIMAL(10,0) NOT NULL,
    LAST_VERSION_ID DECIMAL(10,0),
    FOREIGN KEY (REPO_ID) REFERENCES FS_REPO (ID)
);
CREATE INDEX FS_BACKUP_REPO_FK_INDEX_4 ON FS_BACKUP (REPO_ID);

CREATE TABLE FS_BACKUP_VERSION
(
    ID DECIMAL(10,0) PRIMARY KEY NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    BACKUP_ID DECIMAL(10,0) NOT NULL,
    FOREIGN KEY (BACKUP_ID) REFERENCES FS_BACKUP (ID)
);
CREATE INDEX FS_BACKUP_VERSION_BACKUP_IX ON FS_BACKUP_VERSION (BACKUP_ID);
CREATE INDEX FS_BACKUP_VERSION_CREATED_DATE ON FS_BACKUP_VERSION (CREATED_DATE);

CREATE TABLE FS_STORE
(
    ID DECIMAL(10,0) PRIMARY KEY NOT NULL,
    BACKUP_ID DECIMAL(10,0) NOT NULL,
    PATH VARCHAR(4000) NOT NULL,
    SIZE_BYTE DECIMAL(20,0) NOT NULL,
    SHA512 VARCHAR(500) NOT NULL,
    FOREIGN KEY (BACKUP_ID) REFERENCES FS_BACKUP (ID)
);
CREATE INDEX FS_STORE_BACKUP_FK_INDEX_3 ON FS_STORE (BACKUP_ID);
CREATE INDEX FS_STORE_SHA512_IX ON FS_STORE (SHA512);

CREATE TABLE FS_RESERVE
(
    ID DECIMAL(10,0) PRIMARY KEY NOT NULL,
    BACKUP_ID DECIMAL(10,0) NOT NULL,
    VERSION_ID DECIMAL(10,0) NOT NULL,
    LAST_VERSION_ID DECIMAL(10,0) NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    NAME VARCHAR(500) NOT NULL,
    PATH VARCHAR(4000),
    SIZE_BYTE DECIMAL(20,0) NOT NULL,
    LENGTH DECIMAL(10,0) NOT NULL,
    LAST_MODIFIED TIMESTAMP NOT NULL,
    STORE_ID DECIMAL(10,0),
    FOREIGN KEY (BACKUP_ID) REFERENCES FS_BACKUP (ID),
    FOREIGN KEY (VERSION_ID) REFERENCES FS_BACKUP_VERSION (ID),
    FOREIGN KEY (STORE_ID) REFERENCES FS_STORE (ID)
);
CREATE INDEX FS_RESERVE_BACKUP_FK_INDEX_D ON FS_RESERVE (BACKUP_ID);
CREATE INDEX FS_RESERVE_BACKUP_IX ON FS_RESERVE (BACKUP_ID, VERSION_ID);
CREATE INDEX FS_RESERVE_STORE_FK_INDEX_D ON FS_RESERVE (STORE_ID);
CREATE INDEX FS_RESERVE_VERSION_FK_INDEX_D ON FS_RESERVE (VERSION_ID);

CREATE TABLE FS_MESSAGE
(
    ID DECIMAL(10,0) PRIMARY KEY NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    SUBJECT VARCHAR(1000) NOT NULL,
    TEXT VARCHAR(4000) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    SENT_DATE TIMESTAMP,
    RESEND_COUNTER DECIMAL(10,0) NOT NULL
);
CREATE INDEX FS_MESSAGE_STATUS ON FS_MESSAGE (STATUS);

---------------------------------------------------------------
--DROP TABLE FS_SNAPSHOT_VERSION
--DROP TABLE FS_FS_ITEM